# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a959b13acd12bfd1c2e88729721c7514034e01c6360747ea0c37da6ef11fd70c56d35c9520d336fe757ab7945923bfe2818b3b28bb944806a95670a85db5f37

test:
  secret_key_base: eb25bc10682a7d7d7277c28f2f380e9c04367217a3df5c4a4d17a8a9268ff68131da380e6cced7ed50a16961f932585eaad10e72624c0f9f3cebad1c55bd385a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
